// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllWebUIExtensions() {
  return window['go']['git']['GitController']['AllWebUIExtensions']();
}

export function Branches(arg1) {
  return window['go']['git']['GitController']['Branches'](arg1);
}

export function CheckDifference(arg1, arg2, arg3) {
  return window['go']['git']['GitController']['CheckDifference'](arg1, arg2, arg3);
}

export function Checkout(arg1, arg2) {
  return window['go']['git']['GitController']['Checkout'](arg1, arg2);
}

export function CurrentBranch(arg1) {
  return window['go']['git']['GitController']['CurrentBranch'](arg1);
}

export function CurrentRemote(arg1) {
  return window['go']['git']['GitController']['CurrentRemote'](arg1);
}

export function Fetch(arg1, arg2) {
  return window['go']['git']['GitController']['Fetch'](arg1, arg2);
}

export function Pull(arg1, arg2) {
  return window['go']['git']['GitController']['Pull'](arg1, arg2);
}

export function Remotes(arg1) {
  return window['go']['git']['GitController']['Remotes'](arg1);
}

export function SetContext(arg1) {
  return window['go']['git']['GitController']['SetContext'](arg1);
}
