// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentBranch(arg1) {
  return window['go']['git']['GitController']['CurrentBranch'](arg1);
}

export function CurrentRemote(arg1) {
  return window['go']['git']['GitController']['CurrentRemote'](arg1);
}

export function Remotes(arg1) {
  return window['go']['git']['GitController']['Remotes'](arg1);
}

export function SetContext(arg1) {
  return window['go']['git']['GitController']['SetContext'](arg1);
}
