// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {context} from '../models';

export function GetCurrentProxySetting():Promise<config.ProxyConfig>;

export function GetProxyServiceProtocols():Promise<{[key: string]: string}>;

export function SaveNewProxySetting(arg1:boolean,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string):Promise<boolean>;

export function SetContext(arg1:context.Context):Promise<void>;
