// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearComfyUIConfig() {
  return window['go']['config']['ApplicationSettings']['ClearComfyUIConfig']();
}

export function ClearWebUIConfig() {
  return window['go']['config']['ApplicationSettings']['ClearWebUIConfig']();
}

export function GetCurrentAppBehaviours() {
  return window['go']['config']['ApplicationSettings']['GetCurrentAppBehaviours']();
}

export function GetCurrentComfyUIConfig() {
  return window['go']['config']['ApplicationSettings']['GetCurrentComfyUIConfig']();
}

export function GetCurrentProxySetting() {
  return window['go']['config']['ApplicationSettings']['GetCurrentProxySetting']();
}

export function GetCurrentWebUIConfig() {
  return window['go']['config']['ApplicationSettings']['GetCurrentWebUIConfig']();
}

export function GetProxyServiceProtocols() {
  return window['go']['config']['ApplicationSettings']['GetProxyServiceProtocols']();
}

export function IsPathValid(arg1) {
  return window['go']['config']['ApplicationSettings']['IsPathValid'](arg1);
}

export function SaveNewAppBehaviours(arg1) {
  return window['go']['config']['ApplicationSettings']['SaveNewAppBehaviours'](arg1);
}

export function SaveNewComfyUIConfig(arg1) {
  return window['go']['config']['ApplicationSettings']['SaveNewComfyUIConfig'](arg1);
}

export function SaveNewProxySetting(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['config']['ApplicationSettings']['SaveNewProxySetting'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveNewWebUIConfig(arg1) {
  return window['go']['config']['ApplicationSettings']['SaveNewWebUIConfig'](arg1);
}

export function SelectOneDirectory(arg1) {
  return window['go']['config']['ApplicationSettings']['SelectOneDirectory'](arg1);
}

export function SetContext(arg1) {
  return window['go']['config']['ApplicationSettings']['SetContext'](arg1);
}
