// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {context} from '../models';

export function ClearComfyUIConfig():Promise<boolean>;

export function ClearWebUIConfig():Promise<boolean>;

export function GetCurrentAppBehaviours():Promise<config.AppBehaviours>;

export function GetCurrentComfyUIConfig():Promise<config.ComfyUIConfig>;

export function GetCurrentProxySetting():Promise<config.ProxyConfig>;

export function GetCurrentWebUIConfig():Promise<config.A111StableDiffusionWebUIConfig>;

export function GetProxyServiceProtocols():Promise<{[key: string]: string}>;

export function IsPathValid(arg1:string):Promise<boolean>;

export function SaveNewAppBehaviours(arg1:config.AppBehaviours):Promise<boolean>;

export function SaveNewComfyUIConfig(arg1:config.ComfyUIConfig):Promise<boolean>;

export function SaveNewProxySetting(arg1:boolean,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string):Promise<boolean>;

export function SaveNewWebUIConfig(arg1:config.A111StableDiffusionWebUIConfig):Promise<boolean>;

export function SelectOneDirectory(arg1:any):Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;
