// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentProxySetting() {
  return window['go']['config']['ApplicationSettings']['GetCurrentProxySetting']();
}

export function GetProxyServiceProtocols() {
  return window['go']['config']['ApplicationSettings']['GetProxyServiceProtocols']();
}

export function SaveNewProxySetting(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['config']['ApplicationSettings']['SaveNewProxySetting'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SetContext(arg1) {
  return window['go']['config']['ApplicationSettings']['SetContext'](arg1);
}
