// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BreakModelFileParts(arg1) {
  return window['go']['models']['ModelController']['BreakModelFileParts'](arg1);
}

export function ChooseAndSetFileThumbnail(arg1) {
  return window['go']['models']['ModelController']['ChooseAndSetFileThumbnail'](arg1);
}

export function DeleteFilePrompts(arg1, arg2) {
  return window['go']['models']['ModelController']['DeleteFilePrompts'](arg1, arg2);
}

export function FetchCachedFileInfo(arg1) {
  return window['go']['models']['ModelController']['FetchCachedFileInfo'](arg1);
}

export function FetchModelImage(arg1) {
  return window['go']['models']['ModelController']['FetchModelImage'](arg1);
}

export function FetchModelLocalFiles(arg1) {
  return window['go']['models']['ModelController']['FetchModelLocalFiles'](arg1);
}

export function FetchSameSerialVersions(arg1) {
  return window['go']['models']['ModelController']['FetchSameSerialVersions'](arg1);
}

export function FetchUncachedFileInfo(arg1) {
  return window['go']['models']['ModelController']['FetchUncachedFileInfo'](arg1);
}

export function GetModelSubCategoryDirs(arg1, arg2) {
  return window['go']['models']['ModelController']['GetModelSubCategoryDirs'](arg1, arg2);
}

export function ListModelFiles(arg1, arg2, arg3, arg4) {
  return window['go']['models']['ModelController']['ListModelFiles'](arg1, arg2, arg3, arg4);
}

export function RecordFileBaseModel(arg1, arg2) {
  return window['go']['models']['ModelController']['RecordFileBaseModel'](arg1, arg2);
}

export function RecordFileMemo(arg1, arg2) {
  return window['go']['models']['ModelController']['RecordFileMemo'](arg1, arg2);
}

export function RecordFilePrompts(arg1, arg2) {
  return window['go']['models']['ModelController']['RecordFilePrompts'](arg1, arg2);
}

export function RenameModelFile(arg1, arg2) {
  return window['go']['models']['ModelController']['RenameModelFile'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['models']['ModelController']['SetContext'](arg1);
}

export function SetModelVersionThumbnail(arg1, arg2) {
  return window['go']['models']['ModelController']['SetModelVersionThumbnail'](arg1, arg2);
}
