// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BreakModelFileParts(arg1) {
  return window['go']['models']['ModelController']['BreakModelFileParts'](arg1);
}

export function BreakModelVersionFile(arg1) {
  return window['go']['models']['ModelController']['BreakModelVersionFile'](arg1);
}

export function CheckFileNameExists(arg1, arg2, arg3, arg4) {
  return window['go']['models']['ModelController']['CheckFileNameExists'](arg1, arg2, arg3, arg4);
}

export function CheckModelVersionPrimaryFileSize(arg1) {
  return window['go']['models']['ModelController']['CheckModelVersionPrimaryFileSize'](arg1);
}

export function CheckModelVersionType(arg1) {
  return window['go']['models']['ModelController']['CheckModelVersionType'](arg1);
}

export function CheckUnexistCaches() {
  return window['go']['models']['ModelController']['CheckUnexistCaches']();
}

export function ChooseAndSetFileThumbnail(arg1) {
  return window['go']['models']['ModelController']['ChooseAndSetFileThumbnail'](arg1);
}

export function CopyModelFileLoader(arg1) {
  return window['go']['models']['ModelController']['CopyModelFileLoader'](arg1);
}

export function CopyTextureInversionEmbeddingPrompts(arg1) {
  return window['go']['models']['ModelController']['CopyTextureInversionEmbeddingPrompts'](arg1);
}

export function DeleteCaches(arg1) {
  return window['go']['models']['ModelController']['DeleteCaches'](arg1);
}

export function DeleteFilePrompts(arg1, arg2) {
  return window['go']['models']['ModelController']['DeleteFilePrompts'](arg1, arg2);
}

export function DeleteInvalidCaches() {
  return window['go']['models']['ModelController']['DeleteInvalidCaches']();
}

export function DeleteLocalFiles(arg1) {
  return window['go']['models']['ModelController']['DeleteLocalFiles'](arg1);
}

export function DeleteModelFiles(arg1) {
  return window['go']['models']['ModelController']['DeleteModelFiles'](arg1);
}

export function FetchCachedFileInfo(arg1) {
  return window['go']['models']['ModelController']['FetchCachedFileInfo'](arg1);
}

export function FetchDownloadModelVersion(arg1) {
  return window['go']['models']['ModelController']['FetchDownloadModelVersion'](arg1);
}

export function FetchModelImage(arg1) {
  return window['go']['models']['ModelController']['FetchModelImage'](arg1);
}

export function FetchModelInfo(arg1) {
  return window['go']['models']['ModelController']['FetchModelInfo'](arg1);
}

export function FetchModelInfoByFileHash(arg1) {
  return window['go']['models']['ModelController']['FetchModelInfoByFileHash'](arg1);
}

export function FetchModelLocalFiles(arg1) {
  return window['go']['models']['ModelController']['FetchModelLocalFiles'](arg1);
}

export function FetchModelTags(arg1) {
  return window['go']['models']['ModelController']['FetchModelTags'](arg1);
}

export function FetchModelVersionDescription(arg1) {
  return window['go']['models']['ModelController']['FetchModelVersionDescription'](arg1);
}

export function FetchModelVersionPrimaryFile(arg1) {
  return window['go']['models']['ModelController']['FetchModelVersionPrimaryFile'](arg1);
}

export function FetchSameSerialVersions(arg1) {
  return window['go']['models']['ModelController']['FetchSameSerialVersions'](arg1);
}

export function FetchUncachedFileInfo(arg1) {
  return window['go']['models']['ModelController']['FetchUncachedFileInfo'](arg1);
}

export function GetModelSubCategoryDirs(arg1, arg2) {
  return window['go']['models']['ModelController']['GetModelSubCategoryDirs'](arg1, arg2);
}

export function IsImageAsThumbnail(arg1, arg2) {
  return window['go']['models']['ModelController']['IsImageAsThumbnail'](arg1, arg2);
}

export function IsModelVersionPrimaryFileDownloaded(arg1) {
  return window['go']['models']['ModelController']['IsModelVersionPrimaryFileDownloaded'](arg1);
}

export function ListModelFiles(arg1, arg2, arg3, arg4) {
  return window['go']['models']['ModelController']['ListModelFiles'](arg1, arg2, arg3, arg4);
}

export function RecordFileBaseModel(arg1, arg2) {
  return window['go']['models']['ModelController']['RecordFileBaseModel'](arg1, arg2);
}

export function RecordFileMemo(arg1, arg2) {
  return window['go']['models']['ModelController']['RecordFileMemo'](arg1, arg2);
}

export function RecordFilePrompts(arg1, arg2) {
  return window['go']['models']['ModelController']['RecordFilePrompts'](arg1, arg2);
}

export function RenameModelFile(arg1, arg2) {
  return window['go']['models']['ModelController']['RenameModelFile'](arg1, arg2);
}

export function ScanAllResouces() {
  return window['go']['models']['ModelController']['ScanAllResouces']();
}

export function ScanDuplicateFiles() {
  return window['go']['models']['ModelController']['ScanDuplicateFiles']();
}

export function SetContext(arg1) {
  return window['go']['models']['ModelController']['SetContext'](arg1);
}

export function SetModelVersionThumbnail(arg1, arg2) {
  return window['go']['models']['ModelController']['SetModelVersionThumbnail'](arg1, arg2);
}
