// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetModelSubCategoryDirs(arg1, arg2) {
  return window['go']['models']['ModelController']['GetModelSubCategoryDirs'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['models']['ModelController']['SetContext'](arg1);
}
